name: Main

on: workflow_dispatch

jobs:
  Build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            method: none
            buildArgs: windows
            setupCommand: .\"setup/windows.bat"
            artifactName: windowsBuild-x86_64
            artifactPath: export\release\windows\bin\*
          - name: macOS AArch64
            os: macos-15
            method: none
            buildArgs: mac
            setupCommand: sh ./setup/unix.sh
            artifactName: macOSBuild-arm64
            artifactPath: export/release/macos/bin/*
          - name: Android x32
            os: macos-15
            method: android
            buildArgs: "android -ONLY_ARMV7"
            setupCommand: sh ./setup/unix.sh
            artifactName: androidBuild-x86
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: Android x64
            os: macos-15
            method: android
            buildArgs: "android -arm64"
            setupCommand: sh ./setup/unix.sh
            artifactName: androidBuild-x64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        method: ${{ matrix.method }}
        buildArgs: ${{ matrix.buildArgs }}
        setupCommand: ${{ matrix.setupCommand }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
