name: Main

on: workflow_dispatch

jobs:
  Build:
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: Windows
            os: windows-2022
            buildArgs: windows
            artifactName: windowsBuild-x86_64
            artifactPath: export\release\windows\bin\*
          - name: Android 32 Bits
            os: ubuntu-24.04
            buildArgs: "android -ONLY_ARMV7"
            artifactName: androidBuild32
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: Android 64 Bits
            os: ubuntu-24.04
            buildArgs: "android -arm64"
            artifactName: androidBuild64
            artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
          - name: iOS
            os: macos-15
            buildArgs: "ios -nosign"
            artifactName: iOSBuild
            artifactPath: "export/release/ios/build/Release-iphoneos/*.ipa"
    uses: ./.github/workflows/build.yml
    with:
        name: ${{ matrix.name }}
        os: ${{ matrix.os }}
        buildArgs: ${{ matrix.buildArgs }}
        artifactName: ${{ matrix.artifactName }}
        artifactPath: ${{ matrix.artifactPath }}
